### ISSUE TITLE
Binary Release?

### ISSUE THREAD

**Issue by sherzberg** [bobrik/collectd-docker#17]
Curious if you would be willing to also do a binary release of just the collector binary?

I'd like to use the collector and just drop in into our current collectd environment (which is a docker image) without having to build the go code myself.

**Comment by jtclint** [comment]
+1 for this issue, the problem is we have our own custom metric setup.  I am having to hack all your stuff to make it work correctly.  The other option would be to be able to custom set a Prefix/Postfix somehow.

**Comment by bobrik** [comment]
@sherzberg you can obtain binary for 64 bit linux from docker image that is automatically built for each release. Can this work for you?

@jtclint I don't follow how binary release can solve your problem since you change source code.

**Comment by sherzberg** [comment]
@bobrik ideally, I would like to just curl the binary from the github release instead of pulling the binary from a docker image.

**Comment by jamtur01** [comment]
+1 - would also like.

**Comment by konstantinj** [comment]
+1

**Comment by bobrik** [comment]
[0.4.1](https://github.com/bobrik/collectd-docker/releases/tag/0.4.1) has a signed binary attached.
