### ISSUE TITLE
metrics identifier question

### ISSUE THREAD

**Issue by sherzberg** [bobrik/collectd-docker#20]
The docs say the format should be `collectd.<host>.docker_stats.<app>.<task>.<type>.<metric>`, but the `PUTVAL` is `PUTVAL %s/docker_stats-%s.%s/gauge-%s %d:%d\n`.

From what I gather from https://collectd.org/documentation/manpages/collectd-exec.5.shtml, it looks like the `PUTVAL` should be `PUTVAL %s/docker_stats/%s/%s/gauge-%s %d:%d\n`.

If this is the case, I can send a PR for you.

**Comment by bobrik** [comment]
> An Identifier is of the form host/plugin-instance/type-instance with both instance-parts being optional.

The only reason it works now is that I disable changing `.` to `_` in collectd config, otherwise it would be mess: `collectd.<host>.docker_stats.<app>.<task>-<type>-<metric>`.

Correct me if I'm wrong and it could be better.

**Comment by sherzberg** [comment]
This is a screenshot from graphite web. If the `PUTVAL` would have slashes in between app and task, I would be able to do easier `*` queries.

<img width="255" alt="screenshot 2015-10-08 10 06 15" src="https://cloud.githubusercontent.com/assets/447355/10370411/48ce0568-6da4-11e5-97ea-e85edd60c463.png">

What do you use to visualize metrics?

**Comment by bobrik** [comment]
Are you using my image and config?
