### ISSUE TITLE
Network metrics not collected

### ISSUE THREAD

**Issue by agarbato** [bobrik/collectd-docker#24]
Unable to get network metrics.

Tried also with privileged mode, network mode=host

CentOS 7.1.1503 - selinux disabled
Docker version

[root@myhost ~]# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64

[root@myhost ~]# docker run -d -e GRAPHITE_HOST=mygraphite --net=host --name collectd-mesos --privileged=true -e COLLECTD_HOST=myhost -v /var/run/docker.sock:/var/run/docker.sock bobrik/collectd-docker
7aa44ca3760945ab5fade20949b437d8ea8dba67f82cc88fd0c53142901de4fc

When I run it manually I get all metrics but network.

[root@myhost ~]# docker exec -ti collectd-mesos /bin/bash
root@myhost:/# 
root@myhost:/# /collector  -endpoint="unix:///var/run/docker.sock" --host=mygraphite --interval=100
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.user 1451263065:20780000000
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.active_anon 1451263065:54046720
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_fault 1451263065:13080
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.rss 1451263065:54046720
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.active_file 1451263065:225280
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_in 1451263065:13825
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_out 1451263065:12483
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.unevictable 1451263065:0
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.inactive_file 1451263065:11923456
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.system 1451263065:17780000000
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.total 1451263065:46558770625
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.limit 1451263065:268435456
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.max 1451263065:91095040
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.usage 1451263065:66195456
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.cache 1451263065:12148736
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.inactive_anon 1451263065:0
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.mapped_file 1451263065:4476928
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.rss_huge 1451263065:50331648
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.writeback 1451263065:0

**Comment by bobrik** [comment]
> network mode=host

Docker does not collect network metrics when network mode is `host`.

**Comment by agarbato** [comment]
You're right but network mode=host was only my last attempt.
The problem exist also without network host.

See below:
Any constraint about docker version or any other volume the app need?

[root@myhost ~]# docker run -d -e GRAPHITE_HOST=mygraphite --name collectd-mesos -e COLLECTD_HOST=myhost -v /var/run/docker.sock:/var/run/docker.sock bobrik/collectd-docker1aae2165b044e8c276e9ca651cda18ec07aaa1e56ffae3ae403847b88b49542c
[root@myhost ~]# docker exec -ti collectd-mesos /bin/bash
r
root@1aae2165b044:/# /collector --endpoint="unix://var/run/docker.sock" --host=mygraphite
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_fault 1451321909:14078
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_out 1451321909:17979
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.usage 1451321909:66351104
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.cache 1451321909:12148736
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.rss_huge 1451321909:50331648
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.writeback 1451321909:0
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.total 1451321909:632104226420
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.pg_in 1451321909:14249
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.max 1451321909:93290496
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.inactive_anon 1451321909:0
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.mapped_file 1451321909:4530176
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.unevictable 1451321909:0
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.user 1451321909:224820000000
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-cpu.system 1451321909:198710000000
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.active_file 1451321909:217088
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.inactive_file 1451321909:11931648
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.rss 1451321909:54202368
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.limit 1451321909:134217728
PUTVAL mygraphite/docker_stats-myapp01.default/gauge-memory.active_anon 1451321909:54202368
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.inactive_file 1451321909:10801152
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.writeback 1451321909:0
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-cpu.user 1451321909:152630000000
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.limit 1451321909:67108864
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.inactive_anon 1451321909:0
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.pg_in 1451321909:3655
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.max 1451321909:17874944
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.cache 1451321909:11022336
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.pg_out 1451321909:2237
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.rss 1451321909:5251072
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.rss_huge 1451321909:4194304
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-cpu.system 1451321909:123550000000
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-cpu.total 1451321909:359378123819
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.usage 1451321909:16273408
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.active_anon 1451321909:5251072
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.active_file 1451321909:221184
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.mapped_file 1451321909:3538944
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.pg_fault 1451321909:3085
PUTVAL mygraphite/docker_stats-myapp02.default/gauge-memory.unevictable 1451321909:0

**Comment by bobrik** [comment]
What version are you at? I think 1.9.x should work without issues, previous versions could be broken due to backward incompatible change in docker.

**Comment by agarbato** [comment]
I'm on 1.8.1

[root@myhost ~]# docker version
Client:
Version: 1.8.1
API version: 1.20
Go version: go1.4.2
Git commit: d12ea79
Built: Thu Aug 13 02:19:43 UTC 2015
OS/Arch: linux/amd64

Updating to 1.9 fixed the issue.  Worth to mention it on README ;)
Thanks for your support and your brilliant work.
