### ISSUE TITLE
Can't make ENV variables work

### ISSUE THREAD

**Issue by Tremualin** [bobrik/collectd-docker#27]
I'm trying to set this up to run on top of Mesos and Marathon. The idea is to be able to collect from most of the containers, if not all.

I'm using these ENV variables:
COLLECTD_DOCKER_TASK_ENV=MESOS_TASK_ID
COLLECTD_DOCKER_APP_ENV=MARATHON_APP_ID

I'm also setting these variables to the name of the application deployed:
COLLECTD_DOCKER_APP_ENV_TRIM_PREFIX=app_name
COLLECTD_DOCKER_TASK_ENV_TRIM_PREFIX=app_name

When using COLLECTD_DOCKER_TASK and COLLECTD_DOCKER_APP it works, but It's not practical when having lot of Marathon apps.

Any help is appreciated.

**Comment by bobrik** [comment]
> Can't make ENV variables work
> 
> When using COLLECTD_DOCKER_TASK and COLLECTD_DOCKER_APP it works, but It's not practical when having lot of Marathon apps.

Is it working or not?

**Comment by Tremualin** [comment]
This setup works:
COLLECTD_DOCKER_TASK=task_name
COLLECTD_DOCKER_APP=app_name

But this one doesn't:
COLLECTD_DOCKER_TASK_ENV=MESOS_TASK_ID
COLLECTD_DOCKER_APP_ENV=MARATHON_APP_ID

**Comment by bobrik** [comment]
Can you show me how you run collectd-docker and your containers?
