### ISSUE TITLE
Integrate the plugin in collectd

### ISSUE THREAD

**Issue by kpnarayanan** [bobrik/collectd-docker#29]
Hi,

I am looking for a collectd plugin which can provide resource monitoring data about the individual containers running on the host. In this process, I came across your plugin. 

I have a few questions which I have listed them below:
a) What are the steps that I have to follow in order to build the source code?
b) Is there a way that the plugin can be integrated with an existing version of collectd
c) where is the output of the collectd-docker stored? 

Regards,
Krishnaprasad

**Comment by bobrik** [comment]
a) https://github.com/bobrik/collectd-docker/blob/master/collector/Dockerfile
b) yes, just do the same things outside of docker container
c) graphite, this is mentioned in the readme
