### ISSUE TITLE
Fails to collect any data on Ubuntu / docker-machine virtual box

### ISSUE THREAD

**Issue by RobTaylor76** [bobrik/collectd-docker#30]
Hi,
  i have been trying to get this running for a few hours without any luck.

I start the container as follows...

docker run -d -v /var/run/docker.sock:/var/run/docker.sock \
    -e GRAPHITE_HOST=192.168.99.100 -e COLLECTD_HOST=monitoring \
    bobrik/collectd-docker

The collector program doesn't seem to do anything. it is running and i can see it's process. 

 If i run it from the command line it does nothing... should i expect to see standard output?

I have ruled out an issue with collectd in the container as i ssh'd into the container and enabled cpu stats and wrote these fine to csv and  my graphite server. I've also used wireshark  to establish that collectd polls graphite but sends no data.

I don't think the IP address is the issue as collectd seems to work fine with it if i configure other sources.... i.e cpu.

I am running ubuntu 14.04, docker 1.10.3. I have ran your container directly in ubuntu and using the docker-machine virtual box (boot2docker).  I see the same issue either way ... i.e no data in graphite.

Would you be able to add a diagnostic option maybe?

Do i need to run this as a privileged container?  

It's a shame as i'm about to give a monitoring talk to a local devops group and this seemed ideal for a demo on monitoring docker containers stats.

**Comment by jingzhaoou** [comment]
Ran into the same issue on my Ubuntu machine. Any idea how to resolve it? 

Thanks a lot!
Jingzhao

**Comment by bobrik** [comment]
I run the following to see what graphite should see on `127.0.0.1`:

```
$ docker run --rm -it --net host debian:jessie bash -c 'apt-get update && apt-get install -y netcat && nc -v -l -p 2003'
```

Then I run `collectd-docker` container reporting to `127.0.0.1`:

```
$ docker run --net host -v /var/run/docker.sock:/var/run/docker.sock -e GRAPHITE_HOST=127.0.0.1 -e COLLECTD_HOST=monitoring bobrik/collectd-docker
```

Then I run a container to monitor:

```
$ docker run --rm -it --net host -e COLLECTD_DOCKER_APP=heya debian:jessie
```

Then boom, I see metrics in the first container:

```
collectd.monitoring.docker_stats.heya.default.gauge.memory.pg_in 0.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.cpu.user 10000000.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.cpu.system 0.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.cpu.total 22820567.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.memory.pg_out 0.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.memory.writeback 0.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.memory.inactive_file 0.000000 1460208673
collectd.monitoring.docker_stats.heya.default.gauge.memory.cache 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.inactive_file 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.active_anon 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.mapped_file 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.unevictable 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.writeback 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.limit 0.000000 1460208683
collectd.monitoring.docker_stats.heya.default.gauge.memory.active_file 0.000000 1460208683
```

**Comment by RobTaylor76** [comment]
Hi,
  thanks for the update... it turns out that i hadn't set the COLLECTD_DOCKER_APP  environment variable so it wasn't being logged.

I assumed that all docker containers would be logged by default.

When i added COLLECTD_DOCKER_APP my docker containers appeared in graphite.

Thanks for the prompt response.

Rob
