### ISSUE TITLE
SSL Error?

### ISSUE THREAD

**Issue by stevezau** [bobrik/collectd-docker#41]
Hi,

I seem to be getting the below when starting the container? Not sure why?

exec plugin: exec_read_one: error =   -cert string
exec plugin: exec_read_one: error =         cert path for tls
exec plugin: exec_read_one: error =   -endpoint string
exec plugin: exec_read_one: error =         docker endpoint (default "unix:///var/run/docker.sock")
exec plugin: exec_read_one: error =   -host string
exec plugin: exec_read_one: error =         host to report
exec plugin: exec_read_one: error =   -interval int
exec plugin: exec_read_one: error =         interval to report (default 1)
exec plugin: Program `/usr/bin/collectd-docker-collector' has closed STDERR.

**Comment by bobrik** [comment]
How did you run it?

**Comment by stevezau** [comment]
Command below.. Graphite is listening on 172.17.0.1 port 2003 (i've tested this connection)

docker run -d -v /var/run/docker.sock:/var/run/docker.sock \
    -e GRAPHITE_HOST=172.17.0.1 \
    bobrik/collectd-docker

**Comment by bobrik** [comment]
`COLLECTD_HOST` should be defined.

**Comment by stevezau** [comment]
Maybe i've mis-understood this docker container. I thought it came with collectd, do i need to run collectd somewhere else? What if all i want to do is send data to a graphite endpoint

**Comment by bobrik** [comment]
From README:

> COLLECTD_HOST - host to use in metric name, defaults to MESOS_HOST if defined.

It's just a string to report as host.

**Comment by stevezau** [comment]
Ah, that's what i thought. thanks. makes sense now.
