### ISSUE TITLE
Can't restart a container

### ISSUE THREAD

**Issue by BirgerK** [bobrik/collectd-docker#42]
Doing:
- start a container, everything is fine
- stop the container
- start the container again

expectation:
- container starts like the first time

what happens:
- the container can't start because of `useradd: user 'collectd-docker-collector' already exists`

Seems like this [line](https://github.com/bobrik/collectd-docker/blob/master/docker/run.sh#L28) in the start-script isn't fine.
I guess it will be all fine if the script checks for the existing user.

**Comment by BirgerK** [comment]
Pull-Request is provided. Please take a look.

**Comment by bobrik** [comment]
Thanks!
