### ISSUE TITLE
why not build-commands in dockerfile?

### ISSUE THREAD

**Issue by BirgerK** [bobrik/collectd-docker#44]
Hi there,

while fixing a bug I saw that all build-commands are in an external build.sh. That's not the "docker-way".

Even it's a dedicated docker-repository I can't see a reason why that commands should be collected in a bash-script. If you're interested in, I would migrate that commands from the script to the dockerfile. That would (partially) speed up the build-progress.

Regards

**Comment by bobrik** [comment]
If you can speed up the build process and not make the resulting image bigger, I'm very curious to see how.

**Comment by BirgerK** [comment]
I provided a MR for it.

The new image is about 1MB smaller than previous. I think it's also better readable than before.

With that `ADD`-lines you can see which dedicated files are added from THIS repository to the docker-image. In the previous build-script it was hidden in some `cp`-commands.

I'm no go-expert but maybe it's too much if you add the whole `collector`-dir to the image. it's only needed for the `go restoredep`-command. Maybe even that command isn't needed because of some lines later you get the "binaries" from this. Do you need the dependencies if you have the binaries?

If you got some time, you can take a look on? :)
